title: Bogdan Bystritskiy - iOS Software Engineer
author: Bogdan Bystritskiy
email: b@bystritskiy.com
description: >
  I am an iOS Software Engineer with 3-year experience of iOS programming. This is my blog.
show_excerpts: true

sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Bogdan Bystritskiy
  tagline: iOS Software Engineer
  date_format: "%b %-d, %Y"
  style: blue
  showNav: false
  showPicker: false
  analytics_id: 'UA-64099894-3'
  
  social_links:
    twitter: bystritskiy_b
    github:  bystritskiy
    linkedIn: in/bystritskiy

header_pages:
 - about.md

plugins:
  - jekyll-seo-tag
