title: Bogdan Bystritskiy
author: Bogdan Bystritskiy
email: b@bystritskiy.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true

sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Bogdan Bystritskiy
  tagline: Developer
  date_format: "%b %-d, %Y"
  style: blue
  showNav: false
  showPicker: false

  social_links:
    twitter: bystritskiy_b
    github:  bystritskiy
    linkedIn: in/bystritskiy

header_pages:
 - about.md

plugins:
  - jekyll-seo-tag
